### ISSUE TITLE
Checks are stop after the 6th check

### ISSUE THREAD

**Issue by rustik666** [enlightn/enlightn#2] opened 2021-01-15 08:54 UTC
### Versions

* PHP version: 7.4.8
* Laravel version: 7.30.0
* Enlightn version: 1.0
* Enlightn Pro version (if applicable): n/a

### Description

During the run of the command `php artisan enlightn` we got the next result:

<img width="1642" alt="Screenshot 2021-01-15 at 09 48 48" src="https://user-images.githubusercontent.com/69072017/104703235-5d882580-5717-11eb-8dac-8fe16bfdd109.png">

We checked logs, but there no issues.

### Steps to Reproduce

Install the library via `composer require --dev enlightn/enlightn`. Run the command `php artisan enlightn`.

**Expected behavior:**

All 60 checks are passed.

**Actual behavior:**

Command exited after 6th check.

**Comment by paras-malhotra** [comment] 2021-01-15 09:38
@rustik666, thanks for reporting this. I'm unable to reproduce this on a fresh Laravel 7 application. Steps below:

```bash
 composer create-project --prefer-dist laravel/laravel:^7.0 laravel7-skeleton
cd laravel7-skeleton
composer require --dev enlightn/enlightn
php artisan enlightn
```

I'm also using PHP 7.4 so not sure what the issue is here? Can you try replicating the above steps?

Some other things that you can try:
- Try setting the `base_path` config variable to the folder path where your app code resides. [Documentation here](https://www.laravel-enlightn.com/docs/getting-started/configuration.html#configuring-base-path).
- Try running the enlightn command in some other environment (say local or staging).

Is anyone else facing this issue? Please report here with as much context as you can provide. Thanks!

**Comment by rustik666** [comment] 2021-01-15 14:42
Hi @paras-malhotra !

Thank you very much for the response. I tried to change the config and comment the app path:

```
    'base_path' => [
//        app_path(),
        database_path('migrations'),
        database_path('seeders'),
    ],
```
and after that I got 60 checks. But I'm not sure that in this way app files were correctly analysed.
Do you know any other options to troubleshoot this issue? Can I find the exact reason of execution interrupting? 

Thank you!

**Comment by paras-malhotra** [comment] 2021-01-15 14:48
@rustik666 this may happen if your app folder has some PHP files that are syntactically incorrect (fatal errors if executed). You can identify the real issue and file by either noticing red lines in your IDE or iterating by only including certain paths like say `app_path('Http')` and checking to see if the error persists.

**Comment by rustik666** [comment] 2021-01-15 21:21
@paras-malhotra thank you very much for the advice!

**Comment by paras-malhotra** [comment] 2021-01-15 21:27
Since this issue has been resolved, I'm closing it. Feel free to open a new issue if needed.

**Closed by paras-malhotra** 2021-01-15 21:27 UTC
Labels: needs more info
